CREATE TABLE TB_AGENDA 
    ( 
     ID_AGENDA  NUMBER (6)  NOT NULL , 
     TITULO     VARCHAR2 (85 CHAR)  NOT NULL , 
     DATA_HORA  TIMESTAMP  NOT NULL , 
     ANOTACAO   VARCHAR2 (2500 CHAR) , 
     ID_USUARIO NUMBER (6)  NOT NULL 
    ) 
;

ALTER TABLE TB_AGENDA 
    ADD CONSTRAINT PK_AGENDA PRIMARY KEY ( ID_AGENDA ) ;

CREATE TABLE TB_ANEXO 
    ( 
     ID_ANEXO     NUMBER (6)  NOT NULL , 
     NOME_ARQUIVO VARCHAR2 (255 CHAR)  NOT NULL , 
     TIPO_ARQUIVO VARCHAR2 (50 CHAR)  NOT NULL , 
     URL          VARCHAR2 (255 CHAR)  NOT NULL , 
     TAMANHO_KB   NUMBER , 
     DATA_CRIACAO TIMESTAMP  NOT NULL , 
     ID_USUARIO   NUMBER (6)  NOT NULL 
    ) 
;

ALTER TABLE TB_ANEXO 
    ADD CONSTRAINT PK_ANEXO PRIMARY KEY ( ID_ANEXO ) ;

CREATE TABLE TB_BAIRRO 
    ( 
     ID_BAIRRO NUMBER (6)  NOT NULL , 
     NOME      VARCHAR2 (100 CHAR)  NOT NULL , 
     ID_CIDADE NUMBER (6)  NOT NULL 
    ) 
;

ALTER TABLE TB_BAIRRO 
    ADD CONSTRAINT PK_BAIRRO PRIMARY KEY ( ID_BAIRRO ) ;

CREATE TABLE TB_CIDADE 
    ( 
     ID_CIDADE NUMBER (6)  NOT NULL , 
     NOME      VARCHAR2 (100 CHAR)  NOT NULL , 
     ID_ESTADO NUMBER (6)  NOT NULL 
    ) 
;

ALTER TABLE TB_CIDADE 
    ADD CONSTRAINT PK_CIDADE PRIMARY KEY ( ID_CIDADE ) ;

CREATE TABLE TB_COLEIRA 
    ( 
     ID_COLEIRA    NUMBER (6)  NOT NULL , 
     DATA_HORA     TIMESTAMP  NOT NULL , 
     LATITUDE      NUMBER (10,8)  NOT NULL , 
     LONGITUDE     NUMBER (11,8)  NOT NULL , 
     BATIMENTO_BPM NUMBER (5,1)  NOT NULL , 
     ALERTA        NUMBER (1)  NOT NULL , 
     ID_PET        NUMBER (6)  NOT NULL 
    ) 
;

ALTER TABLE TB_COLEIRA 
    ADD CONSTRAINT PK_COLEIRA PRIMARY KEY ( ID_COLEIRA ) ;

CREATE TABLE TB_CONSULTA 
    ( 
     ID_CONSULTA    NUMBER (6)  NOT NULL , 
     DATA_HORA      TIMESTAMP  NOT NULL , 
     MODALIDADE     VARCHAR2 (15 CHAR)  NOT NULL , 
     STATUS         VARCHAR2 (15 CHAR)  NOT NULL , 
     OBSERVACOES    VARCHAR2 (1000 CHAR) , 
     ID_PET         NUMBER (6)  NOT NULL , 
     ID_VETERINARIO NUMBER (6)  NOT NULL 
    ) 
;

ALTER TABLE TB_CONSULTA 
    ADD CONSTRAINT CK_CONSULTA_STATUS 
    CHECK (STATUS IN ('AGENDADA','REALIZADA','CANCELADA'))
;


ALTER TABLE TB_CONSULTA 
    ADD CONSTRAINT CK_CONSULTA_MODALIDADE 
    CHECK (MODALIDADE IN ('ONLINE','PRESENCIAL'))
;
ALTER TABLE TB_CONSULTA 
    ADD CONSTRAINT PK_CONSULTA PRIMARY KEY ( ID_CONSULTA ) ;

CREATE TABLE TB_ENDERECO 
    ( 
     ID_ENDERECO NUMBER (6)  NOT NULL , 
     LOGRADOURO  VARCHAR2 (120 CHAR)  NOT NULL , 
     NUMERO      VARCHAR2 (10 CHAR)  NOT NULL , 
     COMPLEMENTO VARCHAR2 (50 CHAR)  NOT NULL , 
     CEP         VARCHAR2 (9 CHAR)  NOT NULL , 
     LATITUDE    NUMBER (10,8)  NOT NULL , 
     LONGITUDE   NUMBER (11,8)  NOT NULL , 
     ID_USUARIO  NUMBER (6)  NOT NULL , 
     ID_BAIRRO   NUMBER (6)  NOT NULL 
    ) 
;

ALTER TABLE TB_ENDERECO 
    ADD CONSTRAINT PK_ENDERECO PRIMARY KEY ( ID_ENDERECO ) ;

CREATE TABLE TB_ESPECIE 
    ( 
     ID_ESPECIE NUMBER (6)  NOT NULL , 
     NOME       VARCHAR2 (50 CHAR)  NOT NULL 
    ) 
;

ALTER TABLE TB_ESPECIE 
    ADD CONSTRAINT PK_ESPECIE PRIMARY KEY ( ID_ESPECIE ) ;

CREATE TABLE TB_ESTADO 
    ( 
     ID_ESTADO NUMBER (6)  NOT NULL , 
     NOME      VARCHAR2 (60 CHAR)  NOT NULL , 
     UF        CHAR (2 CHAR)  NOT NULL 
    ) 
;

ALTER TABLE TB_ESTADO 
    ADD CONSTRAINT PK_ESTADO PRIMARY KEY ( ID_ESTADO ) ;

ALTER TABLE TB_ESTADO
    ADD CONSTRAINT UN_ESTADO_UF UNIQUE(UF);

CREATE TABLE TB_HISTORICO_SAUDE 
    ( 
     ID_HISTORICO_SAUDE NUMBER (6)  NOT NULL , 
     EVENTO             VARCHAR2 (100 CHAR)  NOT NULL , 
     DATA_EVENTO        DATE  NOT NULL , 
     DETALHES           VARCHAR2 (200 CHAR) , 
     ID_PET             NUMBER (6)  NOT NULL 
    ) 
;

ALTER TABLE TB_HISTORICO_SAUDE 
    ADD CONSTRAINT PK_HISTORICO_SAUDE PRIMARY KEY ( ID_HISTORICO_SAUDE ) ;

CREATE TABLE TB_LOG_ERRO 
    ( 
     ID_LOG_ERRO    NUMBER (6)  NOT NULL , 
     NOME_PROCEDURE VARCHAR2 (100 CHAR)  NOT NULL , 
     NOME_USUARIO   VARCHAR2 (100 CHAR)  NOT NULL , 
     DATA_ERRO      TIMESTAMP  NOT NULL , 
     CODIGO_ERRO    NUMBER  NOT NULL , 
     MENSAGEM_ERRO  VARCHAR2 (4000 CHAR)  NOT NULL 
    ) 
;

ALTER TABLE TB_LOG_ERRO 
    ADD CONSTRAINT TB_LOG_ERRO_PK PRIMARY KEY ( ID_LOG_ERRO ) ;

CREATE TABLE TB_NOTIFICACAO 
    ( 
     ID_NOTIFICACAO NUMBER (6)  NOT NULL , 
     MENSAGEM       VARCHAR2 (200 CHAR)  NOT NULL , 
     DATA_ENVIO     TIMESTAMP  NOT NULL , 
     LIDA           CHAR (1)  NOT NULL , 
     ID_USUARIO     NUMBER (6)  NOT NULL 
    ) 
;

ALTER TABLE TB_NOTIFICACAO
ADD CONSTRAINT CK_NOTIFICACAO_LIDA
CHECK (LIDA IN ('S', 'N'));

ALTER TABLE TB_NOTIFICACAO 
    ADD CONSTRAINT PK_NOTIFICACAO PRIMARY KEY ( ID_NOTIFICACAO ) ;

CREATE TABLE TB_PET 
    ( 
     ID_PET        NUMBER (6)  NOT NULL , 
     NOME          VARCHAR2 (50 CHAR)  NOT NULL , 
     DT_NASCIMENTO DATE  NOT NULL , 
     SEXO          CHAR (1 CHAR)  NOT NULL , 
     FOTO_URL      VARCHAR2 (255 CHAR)  NOT NULL , 
     ID_TUTOR      NUMBER (6)  NOT NULL , 
     ID_RACA       NUMBER (6)  NOT NULL 
    ) 
;

ALTER TABLE TB_PET 
    ADD CONSTRAINT CK_PET_SEXO 
    CHECK (SEXO IN ('M','F'))
;
ALTER TABLE TB_PET 
    ADD CONSTRAINT FK_PET PRIMARY KEY ( ID_PET ) ;

CREATE TABLE TB_PRESCRICAO 
    ( 
     ID_PRESCRICAO NUMBER (6)  NOT NULL , 
     TIPO          VARCHAR2 (15 CHAR)  NOT NULL , 
     DESCRICAO     VARCHAR2 (200 CHAR)  NOT NULL , 
     POSOLOGIA     VARCHAR2 (350 CHAR) , 
     ID_PRONTUARIO NUMBER (6)  NOT NULL 
    ) 
;

ALTER TABLE TB_PRESCRICAO
ADD CONSTRAINT CK_PRESCRICAO_TIPO
CHECK (TIPO IN ('MEDICAMENTO', 'DIETA', 'RESTRICAO'));

ALTER TABLE TB_PRESCRICAO 
    ADD CONSTRAINT PK_PRESCRICAO PRIMARY KEY ( ID_PRESCRICAO ) ;

CREATE TABLE TB_PRONTUARIO 
    ( 
     ID_PRONTUARIO      NUMBER (6)  NOT NULL , 
     DIAGNOSTICO        VARCHAR2 (500 CHAR)  NOT NULL , 
     TRATAMENTO         VARCHAR2 (500 CHAR) , 
     SINTOMAS           VARCHAR2 (250 CHAR) , 
     PESO_ANIMAL        NUMBER (5,2) , 
     TEMPERATURA        NUMBER (4,1) , 
     EXAMES_SOLICITADOS VARCHAR2 (250 CHAR) , 
     DATA_RETORNO       DATE , 
     ID_CONSULTA        NUMBER (6)  NOT NULL 
    ) 
;
CREATE UNIQUE INDEX TB_PRONTUARIO__IDX ON TB_PRONTUARIO 
    ( 
     ID_CONSULTA ASC 
    ) 
;

ALTER TABLE TB_PRONTUARIO 
    ADD CONSTRAINT PK_PRONTUARIO PRIMARY KEY ( ID_PRONTUARIO ) ;

CREATE TABLE TB_RACA 
    ( 
     ID_RACA    NUMBER (6)  NOT NULL , 
     NOME       VARCHAR2 (100 CHAR)  NOT NULL , 
     PORTE      VARCHAR2 (10 CHAR)  NOT NULL , 
     ID_ESPECIE NUMBER (6)  NOT NULL 
    ) 
;

ALTER TABLE TB_RACA 
    ADD CONSTRAINT CK_RACA_PORTE 
    CHECK (PORTE IN ('PEQUENO','MEDIO','GRANDE'))
;
ALTER TABLE TB_RACA 
    ADD CONSTRAINT PK_RACA PRIMARY KEY ( ID_RACA ) ;

CREATE TABLE TB_TUTOR 
    ( 
     ID_TUTOR      NUMBER (6)  NOT NULL , 
     NOME_TUTOR    VARCHAR2 (100 CHAR)  NOT NULL , 
     CPF           VARCHAR2 (14 CHAR)  NOT NULL , 
     TELEFONE      VARCHAR2 (20 CHAR)  NOT NULL , 
     DT_NASCIMENTO DATE  NOT NULL , 
     ID_USUARIO    NUMBER (6)  NOT NULL 
    ) 
;
CREATE UNIQUE INDEX TB_TUTOR__IDX ON TB_TUTOR 
    ( 
     ID_USUARIO ASC 
    ) 
;

ALTER TABLE TB_TUTOR 
    ADD CONSTRAINT PK_TUTOR PRIMARY KEY ( ID_TUTOR ) ;

ALTER TABLE TB_TUTOR 
    ADD CONSTRAINT UN_TUTOR_CPF UNIQUE ( CPF ) ;

CREATE TABLE TB_USUARIO 
    ( 
     ID_USUARIO   NUMBER (6)  NOT NULL , 
     EMAIL        VARCHAR2 (80 CHAR)  NOT NULL , 
     SENHA        VARCHAR2 (100 CHAR)  NOT NULL , 
     TIPO_USER    VARCHAR2 (35 CHAR)  NOT NULL , 
     DATA_CRIACAO TIMESTAMP  NOT NULL 
    ) 
;

ALTER TABLE TB_USUARIO 
    ADD CONSTRAINT CK_USUARIO_TIPO 
    CHECK (TIPO_USER IN ('TUTOR','VETERINARIO'))
;
ALTER TABLE TB_USUARIO 
    ADD CONSTRAINT PK_USUARIO PRIMARY KEY ( ID_USUARIO ) ;

ALTER TABLE TB_USUARIO 
    ADD CONSTRAINT UN_USUARIO_EMAIL UNIQUE ( EMAIL ) ;

CREATE TABLE TB_VETERINARIO 
    ( 
     ID_VETERINARIO NUMBER (6)  NOT NULL , 
     NOME           VARCHAR2 (100 CHAR)  NOT NULL , 
     CRMV           VARCHAR2 (20 CHAR)  NOT NULL , 
     TELEFONE       VARCHAR2 (20 CHAR)  NOT NULL , 
     ESPECIALIDADE  VARCHAR2 (100 CHAR)  NOT NULL , 
     DT_NASCIMENTO  DATE  NOT NULL , 
     ID_USUARIO     NUMBER (6)  NOT NULL 
    ) 
;
CREATE UNIQUE INDEX TB_VETERINARIO__IDX ON TB_VETERINARIO 
    ( 
     ID_USUARIO ASC 
    ) 
;

ALTER TABLE TB_VETERINARIO 
    ADD CONSTRAINT PK_VETERINARIO PRIMARY KEY ( ID_VETERINARIO ) ;

ALTER TABLE TB_VETERINARIO 
    ADD CONSTRAINT UN_VETERINARIO_CRMV UNIQUE ( CRMV ) ;

ALTER TABLE TB_AGENDA 
    ADD CONSTRAINT FK_AGENDA_USUARIO FOREIGN KEY 
    ( 
     ID_USUARIO
    ) 
    REFERENCES TB_USUARIO 
    ( 
     ID_USUARIO
    ) 
;

ALTER TABLE TB_ANEXO 
    ADD CONSTRAINT FK_ANEXO_USUARIO FOREIGN KEY 
    ( 
     ID_USUARIO
    ) 
    REFERENCES TB_USUARIO 
    ( 
     ID_USUARIO
    ) 
;

ALTER TABLE TB_BAIRRO 
    ADD CONSTRAINT FK_BAIRRO_CIDADE FOREIGN KEY 
    ( 
     ID_CIDADE
    ) 
    REFERENCES TB_CIDADE 
    ( 
     ID_CIDADE
    ) 
;

ALTER TABLE TB_CIDADE 
    ADD CONSTRAINT FK_CIDADE_ESTADO FOREIGN KEY 
    ( 
     ID_ESTADO
    ) 
    REFERENCES TB_ESTADO 
    ( 
     ID_ESTADO
    ) 
;

ALTER TABLE TB_COLEIRA 
    ADD CONSTRAINT FK_COLEIRA_PET FOREIGN KEY 
    ( 
     ID_PET
    ) 
    REFERENCES TB_PET 
    ( 
     ID_PET
    ) 
;

ALTER TABLE TB_CONSULTA 
    ADD CONSTRAINT FK_CONSULTA_PET FOREIGN KEY 
    ( 
     ID_PET
    ) 
    REFERENCES TB_PET 
    ( 
     ID_PET
    ) 
;

ALTER TABLE TB_CONSULTA 
    ADD CONSTRAINT FK_CONSULTA_VETERINARIO FOREIGN KEY 
    ( 
     ID_VETERINARIO
    ) 
    REFERENCES TB_VETERINARIO 
    ( 
     ID_VETERINARIO
    ) 
;

ALTER TABLE TB_ENDERECO 
    ADD CONSTRAINT FK_ENDERECO_BAIRRO FOREIGN KEY 
    ( 
     ID_BAIRRO
    ) 
    REFERENCES TB_BAIRRO 
    ( 
     ID_BAIRRO
    ) 
;

ALTER TABLE TB_ENDERECO 
    ADD CONSTRAINT FK_ENDERECO_USUARIO FOREIGN KEY 
    ( 
     ID_USUARIO
    ) 
    REFERENCES TB_USUARIO 
    ( 
     ID_USUARIO
    ) 
;

ALTER TABLE TB_HISTORICO_SAUDE 
    ADD CONSTRAINT FK_HISTORICO_SAUDE_PET FOREIGN KEY 
    ( 
     ID_PET
    ) 
    REFERENCES TB_PET 
    ( 
     ID_PET
    ) 
;

ALTER TABLE TB_NOTIFICACAO 
    ADD CONSTRAINT FK_NOTIFICACAO_USUARIO FOREIGN KEY 
    ( 
     ID_USUARIO
    ) 
    REFERENCES TB_USUARIO 
    ( 
     ID_USUARIO
    ) 
;

ALTER TABLE TB_PET 
    ADD CONSTRAINT FK_PET_RACA FOREIGN KEY 
    ( 
     ID_RACA
    ) 
    REFERENCES TB_RACA 
    ( 
     ID_RACA
    ) 
;

ALTER TABLE TB_PET 
    ADD CONSTRAINT FK_PET_TUTOR FOREIGN KEY 
    ( 
     ID_TUTOR
    ) 
    REFERENCES TB_TUTOR 
    ( 
     ID_TUTOR
    ) 
;

ALTER TABLE TB_PRESCRICAO 
    ADD CONSTRAINT FK_PRESCRICAO_PRONTUARIO FOREIGN KEY 
    ( 
     ID_PRONTUARIO
    ) 
    REFERENCES TB_PRONTUARIO 
    ( 
     ID_PRONTUARIO
    ) 
;

ALTER TABLE TB_PRONTUARIO 
    ADD CONSTRAINT FK_PRONTUARIO_CONSULTA FOREIGN KEY 
    ( 
     ID_CONSULTA
    ) 
    REFERENCES TB_CONSULTA 
    ( 
     ID_CONSULTA
    ) 
;

ALTER TABLE TB_RACA 
    ADD CONSTRAINT FK_RACA_ESPECIE FOREIGN KEY 
    ( 
     ID_ESPECIE
    ) 
    REFERENCES TB_ESPECIE 
    ( 
     ID_ESPECIE
    ) 
;

ALTER TABLE TB_TUTOR 
    ADD CONSTRAINT FK_TUTOR_USUARIO FOREIGN KEY 
    ( 
     ID_USUARIO
    ) 
    REFERENCES TB_USUARIO 
    ( 
     ID_USUARIO
    ) 
;

ALTER TABLE TB_VETERINARIO 
    ADD CONSTRAINT FK_VETERINARIO_USUARIO FOREIGN KEY 
    ( 
     ID_USUARIO
    ) 
    REFERENCES TB_USUARIO 
    ( 
     ID_USUARIO
    ) 
;

ALTER TABLE TB_TUTOR
MODIFY TELEFONE VARCHAR2(15 CHAR);

ALTER TABLE TB_VETERINARIO
MODIFY TELEFONE VARCHAR2(15 CHAR);

ALTER TABLE TB_VETERINARIO
MODIFY CRMV VARCHAR2(14 CHAR);

ALTER TABLE TB_VETERINARIO
ADD CONSTRAINT CK_VETERINARIO_CRMV
CHECK (
    REGEXP_LIKE(
        CRMV,
        '^CRMV-[A-Z]{2}-[0-9]{5}$'
    )
);

CREATE SEQUENCE SEQ_ESTADO;
 
CREATE SEQUENCE SEQ_CIDADE;
 
CREATE SEQUENCE SEQ_BAIRRO;
 
CREATE SEQUENCE SEQ_ENDERECO;
 
CREATE SEQUENCE SEQ_USUARIO;
 
CREATE SEQUENCE SEQ_TUTOR;
 
CREATE SEQUENCE SEQ_VETERINARIO;
 
CREATE SEQUENCE SEQ_ESPECIE;
 
CREATE SEQUENCE SEQ_RACA;
 
CREATE SEQUENCE SEQ_PET;
 
CREATE SEQUENCE SEQ_CONSULTA;
 
CREATE SEQUENCE SEQ_PRONTUARIO;
 
CREATE SEQUENCE SEQ_PRESCRICAO;
 
CREATE SEQUENCE SEQ_HISTORICO_SAUDE;
 
CREATE SEQUENCE SEQ_COLEIRA;
 
CREATE SEQUENCE SEQ_AGENDA;
 
CREATE SEQUENCE SEQ_NOTIFICACAO;
 
CREATE SEQUENCE SEQ_ANEXO;
 
CREATE SEQUENCE SEQ_LOG_ERRO;
