CREATE SEQUENCE SEQ_CORPO_CELESTE;
CREATE SEQUENCE SEQ_SOLO;
CREATE SEQUENCE SEQ_CLIMA_AMBIENTE;
CREATE SEQUENCE SEQ_VEGETAL;
CREATE SEQUENCE SEQ_REQUISITO_VEGETAL;
CREATE SEQUENCE SEQ_USUARIO_APP;
CREATE SEQUENCE SEQ_SIMULACAO_CULTIVO;
CREATE SEQUENCE SEQ_RELATORIO_VIABILIDADE