
INSERT INTO TB_ESTADO (ID_ESTADO, NOME, UF) VALUES (SEQ_ESTADO.NEXTVAL, 'São Paulo', 'SP');
INSERT INTO TB_ESTADO (ID_ESTADO, NOME, UF) VALUES (SEQ_ESTADO.NEXTVAL, 'Rio de Janeiro', 'RJ');
INSERT INTO TB_ESTADO (ID_ESTADO, NOME, UF) VALUES (SEQ_ESTADO.NEXTVAL, 'Minas Gerais', 'MG');
INSERT INTO TB_ESTADO (ID_ESTADO, NOME, UF) VALUES (SEQ_ESTADO.NEXTVAL, 'Paraná', 'PR');
INSERT INTO TB_ESTADO (ID_ESTADO, NOME, UF) VALUES (SEQ_ESTADO.NEXTVAL, 'Rio Grande do Sul', 'RS');


INSERT INTO TB_CIDADE (ID_CIDADE, NOME, ID_ESTADO) VALUES (SEQ_CIDADE.NEXTVAL, 'São Paulo', 1);
INSERT INTO TB_CIDADE (ID_CIDADE, NOME, ID_ESTADO) VALUES (SEQ_CIDADE.NEXTVAL, 'Campinas', 1);
INSERT INTO TB_CIDADE (ID_CIDADE, NOME, ID_ESTADO) VALUES (SEQ_CIDADE.NEXTVAL, 'Niterói', 2);
INSERT INTO TB_CIDADE (ID_CIDADE, NOME, ID_ESTADO) VALUES (SEQ_CIDADE.NEXTVAL, 'Belo Horizonte', 3);
INSERT INTO TB_CIDADE (ID_CIDADE, NOME, ID_ESTADO) VALUES (SEQ_CIDADE.NEXTVAL, 'Curitiba', 4);


INSERT INTO TB_BAIRRO (ID_BAIRRO, NOME, ID_CIDADE) VALUES (SEQ_BAIRRO.NEXTVAL, 'Pinheiros', 1);
INSERT INTO TB_BAIRRO (ID_BAIRRO, NOME, ID_CIDADE) VALUES (SEQ_BAIRRO.NEXTVAL, 'Vila Madalena', 1);
INSERT INTO TB_BAIRRO (ID_BAIRRO, NOME, ID_CIDADE) VALUES (SEQ_BAIRRO.NEXTVAL, 'Cambuí', 2);
INSERT INTO TB_BAIRRO (ID_BAIRRO, NOME, ID_CIDADE) VALUES (SEQ_BAIRRO.NEXTVAL, 'Icaraí', 3);
INSERT INTO TB_BAIRRO (ID_BAIRRO, NOME, ID_CIDADE) VALUES (SEQ_BAIRRO.NEXTVAL, 'Savassi', 4);


INSERT INTO TB_ESPECIE (ID_ESPECIE, NOME) VALUES (SEQ_ESPECIE.NEXTVAL, 'Cão');
INSERT INTO TB_ESPECIE (ID_ESPECIE, NOME) VALUES (SEQ_ESPECIE.NEXTVAL, 'Gato');
INSERT INTO TB_ESPECIE (ID_ESPECIE, NOME) VALUES (SEQ_ESPECIE.NEXTVAL, 'Ave');
INSERT INTO TB_ESPECIE (ID_ESPECIE, NOME) VALUES (SEQ_ESPECIE.NEXTVAL, 'Roedor');
INSERT INTO TB_ESPECIE (ID_ESPECIE, NOME) VALUES (SEQ_ESPECIE.NEXTVAL, 'Réptil');


INSERT INTO TB_RACA (ID_RACA, NOME, PORTE, ID_ESPECIE) VALUES (SEQ_RACA.NEXTVAL, 'Labrador Retriever', 'GRANDE', 1);
INSERT INTO TB_RACA (ID_RACA, NOME, PORTE, ID_ESPECIE) VALUES (SEQ_RACA.NEXTVAL, 'Siamês', 'PEQUENO', 2);
INSERT INTO TB_RACA (ID_RACA, NOME, PORTE, ID_ESPECIE) VALUES (SEQ_RACA.NEXTVAL, 'Calopsita', 'PEQUENO', 3);
INSERT INTO TB_RACA (ID_RACA, NOME, PORTE, ID_ESPECIE) VALUES (SEQ_RACA.NEXTVAL, 'Poodle', 'MEDIO', 1);
INSERT INTO TB_RACA (ID_RACA, NOME, PORTE, ID_ESPECIE) VALUES (SEQ_RACA.NEXTVAL, 'Persa', 'PEQUENO', 2);


INSERT INTO TB_USUARIO (ID_USUARIO, EMAIL, SENHA, TIPO_USER, DATA_CRIACAO) VALUES (SEQ_USUARIO.NEXTVAL, 'joao.tutor@clyvo.com', 'hash_senha_1', 'TUTOR', SYSTIMESTAMP - 100);
INSERT INTO TB_USUARIO (ID_USUARIO, EMAIL, SENHA, TIPO_USER, DATA_CRIACAO) VALUES (SEQ_USUARIO.NEXTVAL, 'lucas.tutor@clyvo.com', 'hash_senha_2', 'TUTOR', SYSTIMESTAMP - 90);
INSERT INTO TB_USUARIO (ID_USUARIO, EMAIL, SENHA, TIPO_USER, DATA_CRIACAO) VALUES (SEQ_USUARIO.NEXTVAL, 'malu.tutor@clyvo.com', 'hash_senha_3', 'TUTOR', SYSTIMESTAMP - 80);
INSERT INTO TB_USUARIO (ID_USUARIO, EMAIL, SENHA, TIPO_USER, DATA_CRIACAO) VALUES (SEQ_USUARIO.NEXTVAL, 'ana.tutor@clyvo.com', 'hash_senha_4', 'TUTOR', SYSTIMESTAMP - 70);
INSERT INTO TB_USUARIO (ID_USUARIO, EMAIL, SENHA, TIPO_USER, DATA_CRIACAO) VALUES (SEQ_USUARIO.NEXTVAL, 'carlos.tutor@clyvo.com', 'hash_senha_5', 'TUTOR', SYSTIMESTAMP - 60);
INSERT INTO TB_USUARIO (ID_USUARIO, EMAIL, SENHA, TIPO_USER, DATA_CRIACAO) VALUES (SEQ_USUARIO.NEXTVAL, 'vet.roberto@clyvo.com', 'hash_senha_6', 'VETERINARIO', SYSTIMESTAMP - 120);
INSERT INTO TB_USUARIO (ID_USUARIO, EMAIL, SENHA, TIPO_USER, DATA_CRIACAO) VALUES (SEQ_USUARIO.NEXTVAL, 'vet.camila@clyvo.com', 'hash_senha_7', 'VETERINARIO', SYSTIMESTAMP - 110);
INSERT INTO TB_USUARIO (ID_USUARIO, EMAIL, SENHA, TIPO_USER, DATA_CRIACAO) VALUES (SEQ_USUARIO.NEXTVAL, 'vet.fernando@clyvo.com', 'hash_senha_8', 'VETERINARIO', SYSTIMESTAMP - 105);
INSERT INTO TB_USUARIO (ID_USUARIO, EMAIL, SENHA, TIPO_USER, DATA_CRIACAO) VALUES (SEQ_USUARIO.NEXTVAL, 'vet.beatriz@clyvo.com', 'hash_senha_9', 'VETERINARIO', SYSTIMESTAMP - 95);
INSERT INTO TB_USUARIO (ID_USUARIO, EMAIL, SENHA, TIPO_USER, DATA_CRIACAO) VALUES (SEQ_USUARIO.NEXTVAL, 'vet.gabriel@clyvo.com', 'hash_senha_10', 'VETERINARIO', SYSTIMESTAMP - 85);


INSERT INTO TB_TUTOR (ID_TUTOR, NOME_TUTOR, CPF, TELEFONE, DT_NASCIMENTO, ID_USUARIO) VALUES (SEQ_TUTOR.NEXTVAL, 'João Victor', '111.111.111-11', '(11) 99999-0001', TO_DATE('1990-05-10', 'YYYY-MM-DD'), 1);
INSERT INTO TB_TUTOR (ID_TUTOR, NOME_TUTOR, CPF, TELEFONE, DT_NASCIMENTO, ID_USUARIO) VALUES (SEQ_TUTOR.NEXTVAL, 'Lucas Andrade', '222.222.222-22', '(11) 99999-0002', TO_DATE('1992-08-15', 'YYYY-MM-DD'), 2);
INSERT INTO TB_TUTOR (ID_TUTOR, NOME_TUTOR, CPF, TELEFONE, DT_NASCIMENTO, ID_USUARIO) VALUES (SEQ_TUTOR.NEXTVAL, 'Malu Rocha', '333.333.333-33', '(11) 99999-0003', TO_DATE('1995-12-20', 'YYYY-MM-DD'), 3);
INSERT INTO TB_TUTOR (ID_TUTOR, NOME_TUTOR, CPF, TELEFONE, DT_NASCIMENTO, ID_USUARIO) VALUES (SEQ_TUTOR.NEXTVAL, 'Ana Silva', '444.444.444-44', '(11) 99999-0004', TO_DATE('1988-03-25', 'YYYY-MM-DD'), 4);
INSERT INTO TB_TUTOR (ID_TUTOR, NOME_TUTOR, CPF, TELEFONE, DT_NASCIMENTO, ID_USUARIO) VALUES (SEQ_TUTOR.NEXTVAL, 'Carlos Dias', '555.555.555-55', '(11) 99999-0005', TO_DATE('1985-11-30', 'YYYY-MM-DD'), 5);


INSERT INTO TB_VETERINARIO (ID_VETERINARIO, NOME, CRMV, TELEFONE, ESPECIALIDADE, DT_NASCIMENTO, ID_USUARIO) VALUES (SEQ_VETERINARIO.NEXTVAL, 'Dr. Roberto Santos', 'CRMV-SP-12345', '(11) 98888-0001', 'Clínica Geral', TO_DATE('1980-01-15', 'YYYY-MM-DD'), 6);
INSERT INTO TB_VETERINARIO (ID_VETERINARIO, NOME, CRMV, TELEFONE, ESPECIALIDADE, DT_NASCIMENTO, ID_USUARIO) VALUES (SEQ_VETERINARIO.NEXTVAL, 'Dra. Camila Lima', 'CRMV-SP-23456', '(11) 98888-0002', 'Dermatologia', TO_DATE('1985-06-20', 'YYYY-MM-DD'), 7);
INSERT INTO TB_VETERINARIO (ID_VETERINARIO, NOME, CRMV, TELEFONE, ESPECIALIDADE, DT_NASCIMENTO, ID_USUARIO) VALUES (SEQ_VETERINARIO.NEXTVAL, 'Dr. Fernando Costa', 'CRMV-RJ-34567', '(21) 98888-0003', 'Cardiologia', TO_DATE('1978-09-10', 'YYYY-MM-DD'), 8);
INSERT INTO TB_VETERINARIO (ID_VETERINARIO, NOME, CRMV, TELEFONE, ESPECIALIDADE, DT_NASCIMENTO, ID_USUARIO) VALUES (SEQ_VETERINARIO.NEXTVAL, 'Dra. Beatriz Mendes', 'CRMV-MG-45678', '(31) 98888-0004', 'Endocrinologia', TO_DATE('1989-04-05', 'YYYY-MM-DD'), 9);
INSERT INTO TB_VETERINARIO (ID_VETERINARIO, NOME, CRMV, TELEFONE, ESPECIALIDADE, DT_NASCIMENTO, ID_USUARIO) VALUES (SEQ_VETERINARIO.NEXTVAL, 'Dr. Gabriel Ramos', 'CRMV-PR-56789', '(41) 98888-0005', 'Ortopedia', TO_DATE('1982-11-12', 'YYYY-MM-DD'), 10);


INSERT INTO TB_ENDERECO (ID_ENDERECO, LOGRADOURO, NUMERO, COMPLEMENTO, CEP, LATITUDE, LONGITUDE, ID_USUARIO, ID_BAIRRO) VALUES (SEQ_ENDERECO.NEXTVAL, 'Rua dos Pinheiros', '100', 'Apto 12', '05422-000', -23.56123400, -46.68123400, 1, 1);
INSERT INTO TB_ENDERECO (ID_ENDERECO, LOGRADOURO, NUMERO, COMPLEMENTO, CEP, LATITUDE, LONGITUDE, ID_USUARIO, ID_BAIRRO) VALUES (SEQ_ENDERECO.NEXTVAL, 'Rua Harmonia', '250', 'Bloco B', '05435-000', -23.55234500, -46.68901200, 2, 2);
INSERT INTO TB_ENDERECO (ID_ENDERECO, LOGRADOURO, NUMERO, COMPLEMENTO, CEP, LATITUDE, LONGITUDE, ID_USUARIO, ID_BAIRRO) VALUES (SEQ_ENDERECO.NEXTVAL, 'Avenida Coronel Silva', '45', 'Casa', '13025-000', -22.90123400, -47.05123400, 3, 3);
INSERT INTO TB_ENDERECO (ID_ENDERECO, LOGRADOURO, NUMERO, COMPLEMENTO, CEP, LATITUDE, LONGITUDE, ID_USUARIO, ID_BAIRRO) VALUES (SEQ_ENDERECO.NEXTVAL, 'Rua Ator Paulo Gustavo', '500', 'Apto 801', '24230-000', -22.90890000, -43.10123400, 4, 4);
INSERT INTO TB_ENDERECO (ID_ENDERECO, LOGRADOURO, NUMERO, COMPLEMENTO, CEP, LATITUDE, LONGITUDE, ID_USUARIO, ID_BAIRRO) VALUES (SEQ_ENDERECO.NEXTVAL, 'Praça Diogo de Vasconcelos', '12', 'Sala 3', '30140-100', -19.93123400, -43.93123400, 5, 5);


INSERT INTO TB_PET (ID_PET, NOME, DT_NASCIMENTO, SEXO, FOTO_URL, ID_TUTOR, ID_RACA) VALUES (SEQ_PET.NEXTVAL, 'Thor', TO_DATE('2021-05-10', 'YYYY-MM-DD'), 'M', 'https://clyvo.com/photos/thor.jpg', 1, 1);
INSERT INTO TB_PET (ID_PET, NOME, DT_NASCIMENTO, SEXO, FOTO_URL, ID_TUTOR, ID_RACA) VALUES (SEQ_PET.NEXTVAL, 'Mingau', TO_DATE('2022-01-15', 'YYYY-MM-DD'), 'M', 'https://clyvo.com/photos/mingau.jpg', 2, 2);
INSERT INTO TB_PET (ID_PET, NOME, DT_NASCIMENTO, SEXO, FOTO_URL, ID_TUTOR, ID_RACA) VALUES (SEQ_PET.NEXTVAL, 'Aurora', TO_DATE('2023-03-01', 'YYYY-MM-DD'), 'F', 'https://clyvo.com/photos/aurora.jpg', 3, 3);
INSERT INTO TB_PET (ID_PET, NOME, DT_NASCIMENTO, SEXO, FOTO_URL, ID_TUTOR, ID_RACA) VALUES (SEQ_PET.NEXTVAL, 'Mel', TO_DATE('2020-07-20', 'YYYY-MM-DD'), 'F', 'https://clyvo.com/photos/mel.jpg', 4, 4);
INSERT INTO TB_PET (ID_PET, NOME, DT_NASCIMENTO, SEXO, FOTO_URL, ID_TUTOR, ID_RACA) VALUES (SEQ_PET.NEXTVAL, 'Simba', TO_DATE('2021-11-12', 'YYYY-MM-DD'), 'M', 'https://clyvo.com/photos/simba.jpg', 5, 5);


INSERT INTO TB_CONSULTA (ID_CONSULTA, DATA_HORA, MODALIDADE, STATUS, OBSERVACOES, ID_PET, ID_VETERINARIO) VALUES (SEQ_CONSULTA.NEXTVAL, TIMESTAMP '2026-05-02 10:00:00', 'PRESENCIAL', 'REALIZADA', 'Check-up anual e vacinação preventivos', 1, 1);
INSERT INTO TB_CONSULTA (ID_CONSULTA, DATA_HORA, MODALIDADE, STATUS, OBSERVACOES, ID_PET, ID_VETERINARIO) VALUES (SEQ_CONSULTA.NEXTVAL, TIMESTAMP '2026-04-28 14:30:00', 'ONLINE', 'REALIZADA', 'Acompanhamento de rotina dermatológica', 2, 2);
INSERT INTO TB_CONSULTA (ID_CONSULTA, DATA_HORA, MODALIDADE, STATUS, OBSERVACOES, ID_PET, ID_VETERINARIO) VALUES (SEQ_CONSULTA.NEXTVAL, TIMESTAMP '2026-04-12 11:00:00', 'PRESENCIAL', 'REALIZADA', 'Observação comportamental e nutrição', 3, 1);
INSERT INTO TB_CONSULTA (ID_CONSULTA, DATA_HORA, MODALIDADE, STATUS, OBSERVACOES, ID_PET, ID_VETERINARIO) VALUES (SEQ_CONSULTA.NEXTVAL, TIMESTAMP '2026-09-10 09:00:00', 'PRESENCIAL', 'AGENDADA', 'Avaliação pré-operatória', 4, 5);
INSERT INTO TB_CONSULTA (ID_CONSULTA, DATA_HORA, MODALIDADE, STATUS, OBSERVACOES, ID_PET, ID_VETERINARIO) VALUES (SEQ_CONSULTA.NEXTVAL, TIMESTAMP '2026-08-15 16:00:00', 'ONLINE', 'CANCELADA', 'Tutor remarcou por compromisso pessoal', 5, 3);


INSERT INTO TB_PRONTUARIO (ID_PRONTUARIO, DIAGNOSTICO, TRATAMENTO, SINTOMAS, PESO_ANIMAL, TEMPERATURA, EXAMES_SOLICITADOS, DATA_RETORNO, ID_CONSULTA) VALUES (SEQ_PRONTUARIO.NEXTVAL, 'Animal saudável. Retorno preventivo recomendado.', 'Manutenção de dieta e vacinas', 'Sem sintomas agudos', 32.50, 38.5, 'Hemograma Completo', TO_DATE('2027-05-02', 'YYYY-MM-DD'), 1);
INSERT INTO TB_PRONTUARIO (ID_PRONTUARIO, DIAGNOSTICO, TRATAMENTO, SINTOMAS, PESO_ANIMAL, TEMPERATURA, EXAMES_SOLICITADOS, DATA_RETORNO, ID_CONSULTA) VALUES (SEQ_PRONTUARIO.NEXTVAL, 'Leve dermatite atópica', 'Shampoo terapêutico 2x por semana', 'Coceira moderada nas patas', 4.20, 38.2, 'Raspado cutâneo', TO_DATE('2026-06-01', 'YYYY-MM-DD'), 2);
INSERT INTO TB_PRONTUARIO (ID_PRONTUARIO, DIAGNOSTICO, TRATAMENTO, SINTOMAS, PESO_ANIMAL, TEMPERATURA, EXAMES_SOLICITADOS, DATA_RETORNO, ID_CONSULTA) VALUES (SEQ_PRONTUARIO.NEXTVAL, 'Estresse por mudança de ambiente', 'Suplementação vitamínica e enriquecimento ambiental', 'Agitação noturna', 0.11, 40.1, 'Nenhum', TO_DATE('2026-07-12', 'YYYY-MM-DD'), 3);
INSERT INTO TB_PRONTUARIO (ID_PRONTUARIO, DIAGNOSTICO, TRATAMENTO, SINTOMAS, PESO_ANIMAL, TEMPERATURA, EXAMES_SOLICITADOS, DATA_RETORNO, ID_CONSULTA) VALUES (SEQ_PRONTUARIO.NEXTVAL, 'Suspeita de sopro cardíaco leve', 'Cardioproteção preventiva', 'Cansaço fácil após corridas', 12.80, 38.7, 'Ecocardiograma', TO_DATE('2026-10-01', 'YYYY-MM-DD'), 4);
INSERT INTO TB_PRONTUARIO (ID_PRONTUARIO, DIAGNOSTICO, TRATAMENTO, SINTOMAS, PESO_ANIMAL, TEMPERATURA, EXAMES_SOLICITADOS, DATA_RETORNO, ID_CONSULTA) VALUES (SEQ_PRONTUARIO.NEXTVAL, 'Consulta cancelada - Histórico mantido', 'Nenhum', 'Nenhum', 5.10, 38.4, 'Nenhum', NULL, 5);


INSERT INTO TB_PRESCRICAO (ID_PRESCRICAO, TIPO, DESCRICAO, POSOLOGIA, ID_PRONTUARIO) VALUES (SEQ_PRESCRICAO.NEXTVAL, 'MEDICAMENTO', 'Vermífugo Amplo Espectro', '1 comprimido a cada 6 meses', 1);
INSERT INTO TB_PRESCRICAO (ID_PRESCRICAO, TIPO, DESCRICAO, POSOLOGIA, ID_PRONTUARIO) VALUES (SEQ_PRESCRICAO.NEXTVAL, 'MEDICAMENTO', 'Shampoo Hipoalergênico Dermatológico', 'Banhar a cada 3 dias deixando agir por 10 min', 2);
INSERT INTO TB_PRESCRICAO (ID_PRESCRICAO, TIPO, DESCRICAO, POSOLOGIA, ID_PRONTUARIO) VALUES (SEQ_PRESCRICAO.NEXTVAL, 'DIETA', 'Ração Super Premium Cães Adultos', '350g diárias divididas em 2 refeições', 1);
INSERT INTO TB_PRESCRICAO (ID_PRESCRICAO, TIPO, DESCRICAO, POSOLOGIA, ID_PRONTUARIO) VALUES (SEQ_PRESCRICAO.NEXTVAL, 'RESTRICAO', 'Evitar exercícios físicos intensos em horários quentes', 'Até o resultado dos exames cardíacos', 4);
INSERT INTO TB_PRESCRICAO (ID_PRESCRICAO, TIPO, DESCRICAO, POSOLOGIA, ID_PRONTUARIO) VALUES (SEQ_PRESCRICAO.NEXTVAL, 'DIETA', 'Gotas Multivitamínicas para Aves', '2 gotas na água do bebedouro diariamente', 3);


INSERT INTO TB_HISTORICO_SAUDE (ID_HISTORICO_SAUDE, EVENTO, DATA_EVENTO, DETALHES, ID_PET) VALUES (SEQ_HISTORICO_SAUDE.NEXTVAL, 'Vacina Múltipla V10', TO_DATE('2026-05-02', 'YYYY-MM-DD'), 'Aplicada dose anual no membro posterior direito', 1);
INSERT INTO TB_HISTORICO_SAUDE (ID_HISTORICO_SAUDE, EVENTO, DATA_EVENTO, DETALHES, ID_PET) VALUES (SEQ_HISTORICO_SAUDE.NEXTVAL, 'Vacina Antirrábica', TO_DATE('2026-05-02', 'YYYY-MM-DD'), 'Aplicada sem reações adversas', 1);
INSERT INTO TB_HISTORICO_SAUDE (ID_HISTORICO_SAUDE, EVENTO, DATA_EVENTO, DETALHES, ID_PET) VALUES (SEQ_HISTORICO_SAUDE.NEXTVAL, 'Acompanhamento de Vacinação Tríplice Felina', TO_DATE('2026-04-28', 'YYYY-MM-DD'), 'Reforço agendado para o próximo mês', 2);
INSERT INTO TB_HISTORICO_SAUDE (ID_HISTORICO_SAUDE, EVENTO, DATA_EVENTO, DETALHES, ID_PET) VALUES (SEQ_HISTORICO_SAUDE.NEXTVAL, 'Corte de unhas e asa', TO_DATE('2026-04-12', 'YYYY-MM-DD'), 'Procedimento preventivo de rotina', 3);
INSERT INTO TB_HISTORICO_SAUDE (ID_HISTORICO_SAUDE, EVENTO, DATA_EVENTO, DETALHES, ID_PET) VALUES (SEQ_HISTORICO_SAUDE.NEXTVAL, 'Perfil Bioquímico Renal', TO_DATE('2026-03-10', 'YYYY-MM-DD'), 'Valores dentro da normalidade para a idade', 4);


INSERT INTO TB_COLEIRA (ID_COLEIRA, DATA_HORA, LATITUDE, LONGITUDE, BATIMENTO_BPM, ALERTA, ID_PET) VALUES (SEQ_COLEIRA.NEXTVAL, TIMESTAMP '2026-09-04 08:00:00', -23.56123400, -46.68123400, 85.0, 0, 1);
INSERT INTO TB_COLEIRA (ID_COLEIRA, DATA_HORA, LATITUDE, LONGITUDE, BATIMENTO_BPM, ALERTA, ID_PET) VALUES (SEQ_COLEIRA.NEXTVAL, TIMESTAMP '2026-09-04 12:30:00', -23.56150000, -46.68190000, 145.5, 1, 1); -- Alerta taquicardia
INSERT INTO TB_COLEIRA (ID_COLEIRA, DATA_HORA, LATITUDE, LONGITUDE, BATIMENTO_BPM, ALERTA, ID_PET) VALUES (SEQ_COLEIRA.NEXTVAL, TIMESTAMP '2026-09-04 09:15:00', -23.55234500, -46.68901200, 110.0, 0, 2);
INSERT INTO TB_COLEIRA (ID_COLEIRA, DATA_HORA, LATITUDE, LONGITUDE, BATIMENTO_BPM, ALERTA, ID_PET) VALUES (SEQ_COLEIRA.NEXTVAL, TIMESTAMP '2026-09-04 10:00:00', -22.90890000, -43.10123400, 95.2, 0, 4);
INSERT INTO TB_COLEIRA (ID_COLEIRA, DATA_HORA, LATITUDE, LONGITUDE, BATIMENTO_BPM, ALERTA, ID_PET) VALUES (SEQ_COLEIRA.NEXTVAL, TIMESTAMP '2026-09-04 11:45:00', -19.93123400, -43.93123400, 102.8, 0, 5);


INSERT INTO TB_AGENDA (ID_AGENDA, TITULO, DATA_HORA, ANOTACAO, ID_USUARIO) VALUES (SEQ_AGENDA.NEXTVAL, 'Retorno Preventivo Thor', TIMESTAMP '2026-09-15 09:30:00', 'Verificar evolução das vacinas e peso do animal', 1);
INSERT INTO TB_AGENDA (ID_AGENDA, TITULO, DATA_HORA, ANOTACAO, ID_USUARIO) VALUES (SEQ_AGENDA.NEXTVAL, 'Aplicação de Shampoo Terapêutico', TIMESTAMP '2026-09-07 10:00:00', 'Lembrar de deixar o produto agir por 10 minutos no Mingau', 2);
INSERT INTO TB_AGENDA (ID_AGENDA, TITULO, DATA_HORA, ANOTACAO, ID_USUARIO) VALUES (SEQ_AGENDA.NEXTVAL, 'Reunião Clinica Semanal', TIMESTAMP '2026-09-08 08:00:00', 'Alinhamento da equipe de veterinários e cirurgias', 6);
INSERT INTO TB_AGENDA (ID_AGENDA, TITULO, DATA_HORA, ANOTACAO, ID_USUARIO) VALUES (SEQ_AGENDA.NEXTVAL, 'Atendimento Exótico - Calopsita', TIMESTAMP '2026-09-12 14:00:00', 'Preparar sala climatizada para recepção da Aurora', 7);
INSERT INTO TB_AGENDA (ID_AGENDA, TITULO, DATA_HORA, ANOTACAO, ID_USUARIO) VALUES (SEQ_AGENDA.NEXTVAL, 'Check-up Preventivo Mel', TIMESTAMP '2026-09-20 15:00:00', 'Coleta de sangue para perfil renal e hepático', 4);


INSERT INTO TB_NOTIFICACAO (ID_NOTIFICACAO, MENSAGEM, DATA_ENVIO, LIDA, ID_USUARIO) VALUES (SEQ_NOTIFICACAO.NEXTVAL, 'Lembrete: O retorno preventivo do pet Thor é no próximo mês.', TIMESTAMP '2026-09-01 09:00:00', 'S', 1);
INSERT INTO TB_NOTIFICACAO (ID_NOTIFICACAO, MENSAGEM, DATA_ENVIO, LIDA, ID_USUARIO) VALUES (SEQ_NOTIFICACAO.NEXTVAL, 'Alerta IoT: Alteração na frequência cardíaca registrada pela coleira do Thor.', TIMESTAMP '2026-09-04 12:31:00', 'N', 1);
INSERT INTO TB_NOTIFICACAO (ID_NOTIFICACAO, MENSAGEM, DATA_ENVIO, LIDA, ID_USUARIO) VALUES (SEQ_NOTIFICACAO.NEXTVAL, 'Acompanhamento de vacinação do pet Mingau pendente.', TIMESTAMP '2026-09-02 11:20:00', 'N', 2);
INSERT INTO TB_NOTIFICACAO (ID_NOTIFICACAO, MENSAGEM, DATA_ENVIO, LIDA, ID_USUARIO) VALUES (SEQ_NOTIFICACAO.NEXTVAL, 'Sua consulta online foi agendada com sucesso com Dr. Roberto.', TIMESTAMP '2026-08-30 14:00:00', 'S', 3);
INSERT INTO TB_NOTIFICACAO (ID_NOTIFICACAO, MENSAGEM, DATA_ENVIO, LIDA, ID_USUARIO) VALUES (SEQ_NOTIFICACAO.NEXTVAL, 'Novo prontuário clínico disponibilizado no seu aplicativo.', TIMESTAMP '2026-05-02 11:30:00', 'S', 1);


INSERT INTO TB_ANEXO (ID_ANEXO, NOME_ARQUIVO, TIPO_ARQUIVO, URL, TAMANHO_KB, DATA_CRIACAO, ID_USUARIO) VALUES (SEQ_ANEXO.NEXTVAL, 'exame_sangue_thor.pdf', 'application/pdf', 'https://clyvo.com/docs/exame_sangue_thor.pdf', 1024, TIMESTAMP '2026-05-02 11:00:00', 1);
INSERT INTO TB_ANEXO (ID_ANEXO, NOME_ARQUIVO, TIPO_ARQUIVO, URL, TAMANHO_KB, DATA_CRIACAO, ID_USUARIO) VALUES (SEQ_ANEXO.NEXTVAL, 'laudo_dermatologico_mingau.pdf', 'application/pdf', 'https://clyvo.com/docs/laudo_dermatologico.pdf', 2048, TIMESTAMP '2026-04-28 15:00:00', 2);
INSERT INTO TB_ANEXO (ID_ANEXO, NOME_ARQUIVO, TIPO_ARQUIVO, URL, TAMANHO_KB, DATA_CRIACAO, ID_USUARIO) VALUES (SEQ_ANEXO.NEXTVAL, 'raio_x_aurora.png', 'image/png', 'https://clyvo.com/docs/raio_x_aurora.png', 4096, TIMESTAMP '2026-04-12 12:00:00', 3);
INSERT INTO TB_ANEXO (ID_ANEXO, NOME_ARQUIVO, TIPO_ARQUIVO, URL, TAMANHO_KB, DATA_CRIACAO, ID_USUARIO) VALUES (SEQ_ANEXO.NEXTVAL, 'ecocardiograma_mel.pdf', 'application/pdf', 'https://clyvo.com/docs/eco_mel.pdf', 1536, TIMESTAMP '2026-03-10 16:30:00', 4);
INSERT INTO TB_ANEXO (ID_ANEXO, NOME_ARQUIVO, TIPO_ARQUIVO, URL, TAMANHO_KB, DATA_CRIACAO, ID_USUARIO) VALUES (SEQ_ANEXO.NEXTVAL, 'carteira_vacinacao_simba.jpg', 'image/jpeg', 'https://clyvo.com/docs/vacinas_simba.jpg', 512, TIMESTAMP '2026-01-20 10:15:00', 5);

COMMIT;