-- 1. TABELAS AUXILIARES E LOCALIZAÇÃO
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='TB_ESTADO' AND xtype='U')
BEGIN
    CREATE TABLE TB_ESTADO (
        ID_ESTADO INT PRIMARY KEY,
        NOME VARCHAR(60) NOT NULL,
        UF CHAR(2) NOT NULL CONSTRAINT UN_ESTADO_UF UNIQUE
    );
END;

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='TB_CIDADE' AND xtype='U')
BEGIN
    CREATE TABLE TB_CIDADE (
        ID_CIDADE INT PRIMARY KEY,
        NOME VARCHAR(100) NOT NULL,
        ID_ESTADO INT NOT NULL CONSTRAINT FK_CIDADE_ESTADO REFERENCES TB_ESTADO(ID_ESTADO)
    );
END;

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='TB_BAIRRO' AND xtype='U')
BEGIN
    CREATE TABLE TB_BAIRRO (
        ID_BAIRRO INT PRIMARY KEY,
        NOME VARCHAR(100) NOT NULL,
        ID_CIDADE INT NOT NULL CONSTRAINT FK_BAIRRO_CIDADE REFERENCES TB_CIDADE(ID_CIDADE)
    );
END;

-- 2. TABELAS DE USUÁRIOS E PERFIS
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='TB_USUARIO' AND xtype='U')
BEGIN
    CREATE TABLE TB_USUARIO (
        ID_USUARIO INT PRIMARY KEY,
        EMAIL VARCHAR(80) NOT NULL CONSTRAINT UN_USUARIO_EMAIL UNIQUE,
        SENHA VARCHAR(100) NOT NULL,
        TIPO_USER VARCHAR(35) NOT NULL CONSTRAINT CK_USUARIO_TIPO CHECK (TIPO_USER IN ('TUTOR','VETERINARIO')),
        DATA_CRIACAO DATETIME2 NOT NULL DEFAULT SYSDATETIMEOFFSET() AT TIME ZONE 'E. South America Standard Time'
    );
END;

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='TB_TUTOR' AND xtype='U')
BEGIN
    CREATE TABLE TB_TUTOR (
        ID_TUTOR INT PRIMARY KEY,
        NOME_TUTOR VARCHAR(100) NOT NULL,
        CPF VARCHAR(14) NOT NULL CONSTRAINT UN_TUTOR_CPF UNIQUE,
        TELEFONE VARCHAR(15) NOT NULL,
        DT_NASCIMENTO DATE NOT NULL,
        ID_USUARIO INT NOT NULL CONSTRAINT FK_TUTOR_USUARIO REFERENCES TB_USUARIO(ID_USUARIO)
    );
END;

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='TB_VETERINARIO' AND xtype='U')
BEGIN
    CREATE TABLE TB_VETERINARIO (
        ID_VETERINARIO INT PRIMARY KEY,
        NOME VARCHAR(100) NOT NULL,
        CRMV VARCHAR(14) NOT NULL CONSTRAINT UN_VETERINARIO_CRMV UNIQUE,
        TELEFONE VARCHAR(15) NOT NULL,
        ESPECIALIDADE VARCHAR(100) NOT NULL,
        DT_NASCIMENTO DATE NOT NULL,
        ID_USUARIO INT NOT NULL CONSTRAINT FK_VETERINARIO_USUARIO REFERENCES TB_USUARIO(ID_USUARIO)
    );
END;

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='TB_ENDERECO' AND xtype='U')
BEGIN
    CREATE TABLE TB_ENDERECO (
        ID_ENDERECO INT PRIMARY KEY,
        LOGRADOURO VARCHAR(120) NOT NULL,
        NUMERO VARCHAR(10) NOT NULL,
        COMPLEMENTO VARCHAR(50) NOT NULL,
        CEP VARCHAR(9) NOT NULL,
        LATITUDE DECIMAL(10,8) NOT NULL,
        LONGITUDE DECIMAL(11,8) NOT NULL,
        ID_USUARIO INT NOT NULL CONSTRAINT FK_ENDERECO_USUARIO REFERENCES TB_USUARIO(ID_USUARIO),
        ID_BAIRRO INT NOT NULL CONSTRAINT FK_ENDERECO_BAIRRO REFERENCES TB_BAIRRO(ID_BAIRRO)
    );
END;

-- 3. DOMÍNIO VETERINÁRIO (PETS E RAÇAS)
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='TB_ESPECIE' AND xtype='U')
BEGIN
    CREATE TABLE TB_ESPECIE (
        ID_ESPECIE INT PRIMARY KEY,
        NOME VARCHAR(50) NOT NULL
    );
END;

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='TB_RACA' AND xtype='U')
BEGIN
    CREATE TABLE TB_RACA (
        ID_RACA INT PRIMARY KEY,
        NOME VARCHAR(100) NOT NULL,
        PORTE VARCHAR(10) NOT NULL CONSTRAINT CK_RACA_PORTE CHECK (PORTE IN ('PEQUENO','MEDIO','GRANDE')),
        ID_ESPECIE INT NOT NULL CONSTRAINT FK_RACA_ESPECIE REFERENCES TB_ESPECIE(ID_ESPECIE)
    );
END;

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='TB_PET' AND xtype='U')
BEGIN
    CREATE TABLE TB_PET (
        ID_PET INT PRIMARY KEY,
        NOME VARCHAR(50) NOT NULL,
        DT_NASCIMENTO DATE NOT NULL,
        SEXO CHAR(1) NOT NULL CONSTRAINT CK_PET_SEXO CHECK (SEXO IN ('M','F')),
        FOTO_URL VARCHAR(255) NOT NULL,
        ID_TUTOR INT NOT NULL CONSTRAINT FK_PET_TUTOR REFERENCES TB_TUTOR(ID_TUTOR),
        ID_RACA INT NOT NULL CONSTRAINT FK_PET_RACA REFERENCES TB_RACA(ID_RACA)
    );
END;

-- 4. CONSULTAS, PRONTUÁRIOS E PRESCRIÇÕES
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='TB_CONSULTA' AND xtype='U')
BEGIN
    CREATE TABLE TB_CONSULTA (
        ID_CONSULTA INT PRIMARY KEY,
        DATA_HORA DATETIME2 NOT NULL,
        MODALIDADE VARCHAR(15) NOT NULL CONSTRAINT CK_CONSULTA_MODALIDADE CHECK (MODALIDADE IN ('ONLINE','PRESENCIAL')),
        STATUS VARCHAR(15) NOT NULL CONSTRAINT CK_CONSULTA_STATUS CHECK (STATUS IN ('AGENDADA','REALIZADA','CANCELADA')),
        OBSERVACOES VARCHAR(1000),
        ID_PET INT NOT NULL CONSTRAINT FK_CONSULTA_PET REFERENCES TB_PET(ID_PET),
        ID_VETERINARIO INT NOT NULL CONSTRAINT FK_CONSULTA_VETERINARIO REFERENCES TB_VETERINARIO(ID_VETERINARIO)
    );
END;

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='TB_PRONTUARIO' AND xtype='U')
BEGIN
    CREATE TABLE TB_PRONTUARIO (
        ID_PRONTUARIO INT PRIMARY KEY,
        DIAGNOSTICO VARCHAR(500) NOT NULL,
        TRATAMENTO VARCHAR(500),
        SINTOMAS VARCHAR(250),
        PESO_ANIMAL DECIMAL(5,2),
        TEMPERATURA DECIMAL(4,1),
        EXAMES_SOLICITADOS VARCHAR(250),
        DATA_RETORNO DATE,
        ID_CONSULTA INT NOT NULL CONSTRAINT FK_PRONTUARIO_CONSULTA REFERENCES TB_CONSULTA(ID_CONSULTA)
    );
END;

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='TB_PRESCRICAO' AND xtype='U')
BEGIN
    CREATE TABLE TB_PRESCRICAO (
        ID_PRESCRICAO INT PRIMARY KEY,
        TIPO VARCHAR(15) NOT NULL CONSTRAINT CK_PRESCRICAO_TIPO CHECK (TIPO IN ('MEDICAMENTO', 'DIETA', 'RESTRICAO')),
        DESCRICAO VARCHAR(200) NOT NULL,
        POSOLOGIA VARCHAR(350),
        ID_PRONTUARIO INT NOT NULL CONSTRAINT FK_PRESCRICAO_PRONTUARIO REFERENCES TB_PRONTUARIO(ID_PRONTUARIO)
    );
END;

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='TB_HISTORICO_SAUDE' AND xtype='U')
BEGIN
    CREATE TABLE TB_HISTORICO_SAUDE (
        ID_HISTORICO_SAUDE INT PRIMARY KEY,
        EVENTO VARCHAR(100) NOT NULL,
        DATA_EVENTO DATE NOT NULL,
        DETALHES VARCHAR(200),
        ID_PET INT NOT NULL CONSTRAINT FK_HISTORICO_SAUDE_PET REFERENCES TB_PET(ID_PET)
    );
END;

-- 5. RECURSOS AUXILIARES E IOT
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='TB_COLEIRA' AND xtype='U')
BEGIN
    CREATE TABLE TB_COLEIRA (
        ID_COLEIRA INT PRIMARY KEY,
        DATA_HORA DATETIME2 NOT NULL,
        LATITUDE DECIMAL(10,8) NOT NULL,
        LONGITUDE DECIMAL(11,8) NOT NULL,
        BATIMENTO_BPM DECIMAL(5,1) NOT NULL,
        ALERTA INT NOT NULL,
        ID_PET INT NOT NULL CONSTRAINT FK_COLEIRA_PET REFERENCES TB_PET(ID_PET)
    );
END;

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='TB_AGENDA' AND xtype='U')
BEGIN
    CREATE TABLE TB_AGENDA (
        ID_AGENDA INT PRIMARY KEY,
        TITULO VARCHAR(85) NOT NULL,
        DATA_HORA DATETIME2 NOT NULL,
        ANOTACAO VARCHAR(2500),
        ID_USUARIO INT NOT NULL CONSTRAINT FK_AGENDA_USUARIO REFERENCES TB_USUARIO(ID_USUARIO)
    );
END;

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='TB_NOTIFICACAO' AND xtype='U')
BEGIN
    CREATE TABLE TB_NOTIFICACAO (
        ID_NOTIFICACAO INT PRIMARY KEY,
        MENSAGEM VARCHAR(200) NOT NULL,
        DATA_ENVIO DATETIME2 NOT NULL,
        LIDA CHAR(1) NOT NULL CONSTRAINT CK_NOTIFICACAO_LIDA CHECK (LIDA IN ('S', 'N')),
        ID_USUARIO INT NOT NULL CONSTRAINT FK_NOTIFICACAO_USUARIO REFERENCES TB_USUARIO(ID_USUARIO)
    );
END;

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='TB_ANEXO' AND xtype='U')
BEGIN
    CREATE TABLE TB_ANEXO (
        ID_ANEXO INT PRIMARY KEY,
        NOME_ARQUIVO VARCHAR(255) NOT NULL,
        TIPO_ARQUIVO VARCHAR(50) NOT NULL,
        URL VARCHAR(255) NOT NULL,
        TAMANHO_KB INT,
        DATA_CRIACAO DATETIME2 NOT NULL,
        ID_USUARIO INT NOT NULL CONSTRAINT FK_ANEXO_USUARIO REFERENCES TB_USUARIO(ID_USUARIO)
    );
END;

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='TB_LOG_ERRO' AND xtype='U')
BEGIN
    CREATE TABLE TB_LOG_ERRO (
        ID_LOG_ERRO INT PRIMARY KEY,
        NOME_PROCEDURE VARCHAR(100) NOT NULL,
        NOME_USUARIO VARCHAR(100) NOT NULL,
        DATA_ERRO DATETIME2 NOT NULL,
        CODIGO_ERRO INT NOT NULL,
        MENSAGEM_ERRO VARCHAR(4000) NOT NULL
    );
END;

-- =======================================================
-- SEQUÊNCIAS PARA HIBERNATE / JPA
-- =======================================================
-- Padrão Naming Convention Hibernate ({tabela}_sequence)
IF NOT EXISTS (SELECT * FROM sys.sequences WHERE name='usuario_sequence')
    CREATE SEQUENCE usuario_sequence START WITH 1 INCREMENT BY 1;

IF NOT EXISTS (SELECT * FROM sys.sequences WHERE name='tutor_sequence')
    CREATE SEQUENCE tutor_sequence START WITH 1 INCREMENT BY 1;

IF NOT EXISTS (SELECT * FROM sys.sequences WHERE name='veterinario_sequence')
    CREATE SEQUENCE veterinario_sequence START WITH 1 INCREMENT BY 1;

IF NOT EXISTS (SELECT * FROM sys.sequences WHERE name='pet_sequence')
    CREATE SEQUENCE pet_sequence START WITH 1 INCREMENT BY 1;

IF NOT EXISTS (SELECT * FROM sys.sequences WHERE name='especie_sequence')
    CREATE SEQUENCE especie_sequence START WITH 1 INCREMENT BY 1;

IF NOT EXISTS (SELECT * FROM sys.sequences WHERE name='raca_sequence')
    CREATE SEQUENCE raca_sequence START WITH 1 INCREMENT BY 1;

IF NOT EXISTS (SELECT * FROM sys.sequences WHERE name='consulta_sequence')
    CREATE SEQUENCE consulta_sequence START WITH 1 INCREMENT BY 1;

IF NOT EXISTS (SELECT * FROM sys.sequences WHERE name='prontuario_sequence')
    CREATE SEQUENCE prontuario_sequence START WITH 1 INCREMENT BY 1;

IF NOT EXISTS (SELECT * FROM sys.sequences WHERE name='prescricao_sequence')
    CREATE SEQUENCE prescricao_sequence START WITH 1 INCREMENT BY 1;

IF NOT EXISTS (SELECT * FROM sys.sequences WHERE name='notificacao_sequence')
    CREATE SEQUENCE notificacao_sequence START WITH 1 INCREMENT BY 1;

IF NOT EXISTS (SELECT * FROM sys.sequences WHERE name='anexo_sequence')
    CREATE SEQUENCE anexo_sequence START WITH 1 INCREMENT BY 1;

IF NOT EXISTS (SELECT * FROM sys.sequences WHERE name='agenda_sequence')
    CREATE SEQUENCE agenda_sequence START WITH 1 INCREMENT BY 1;

IF NOT EXISTS (SELECT * FROM sys.sequences WHERE name='coleira_sequence')
    CREATE SEQUENCE coleira_sequence START WITH 1 INCREMENT BY 1;

-- Padrão Customizado Oracle/SQL Server (SEQ_{TABELA})
IF NOT EXISTS (SELECT * FROM sys.sequences WHERE name='SEQ_USUARIO')
    CREATE SEQUENCE SEQ_USUARIO START WITH 1 INCREMENT BY 1;

IF NOT EXISTS (SELECT * FROM sys.sequences WHERE name='SEQ_TUTOR')
    CREATE SEQUENCE SEQ_TUTOR START WITH 1 INCREMENT BY 1;

IF NOT EXISTS (SELECT * FROM sys.sequences WHERE name='SEQ_VETERINARIO')
    CREATE SEQUENCE SEQ_VETERINARIO START WITH 1 INCREMENT BY 1;

IF NOT EXISTS (SELECT * FROM sys.sequences WHERE name='SEQ_PET')
    CREATE SEQUENCE SEQ_PET START WITH 1 INCREMENT BY 1;

IF NOT EXISTS (SELECT * FROM sys.sequences WHERE name='SEQ_ESPECIE')
    CREATE SEQUENCE SEQ_ESPECIE START WITH 1 INCREMENT BY 1;

IF NOT EXISTS (SELECT * FROM sys.sequences WHERE name='SEQ_RACA')
    CREATE SEQUENCE SEQ_RACA START WITH 1 INCREMENT BY 1;

IF NOT EXISTS (SELECT * FROM sys.sequences WHERE name='SEQ_CONSULTA')
    CREATE SEQUENCE SEQ_CONSULTA START WITH 1 INCREMENT BY 1;

IF NOT EXISTS (SELECT * FROM sys.sequences WHERE name='SEQ_PRONTUARIO')
    CREATE SEQUENCE SEQ_PRONTUARIO START WITH 1 INCREMENT BY 1;

IF NOT EXISTS (SELECT * FROM sys.sequences WHERE name='SEQ_PRESCRICAO')
    CREATE SEQUENCE SEQ_PRESCRICAO START WITH 1 INCREMENT BY 1;

IF NOT EXISTS (SELECT * FROM sys.sequences WHERE name='SEQ_NOTIFICACAO')
    CREATE SEQUENCE SEQ_NOTIFICACAO START WITH 1 INCREMENT BY 1;

IF NOT EXISTS (SELECT * FROM sys.sequences WHERE name='SEQ_ANEXO')
    CREATE SEQUENCE SEQ_ANEXO START WITH 1 INCREMENT BY 1;

IF NOT EXISTS (SELECT * FROM sys.sequences WHERE name='SEQ_AGENDA')
    CREATE SEQUENCE SEQ_AGENDA START WITH 1 INCREMENT BY 1;

IF NOT EXISTS (SELECT * FROM sys.sequences WHERE name='SEQ_COLEIRA')
    CREATE SEQUENCE SEQ_COLEIRA START WITH 1 INCREMENT BY 1;

IF NOT EXISTS (SELECT * FROM sys.sequences WHERE name='SEQ_RELATORIO_VIABILIDADE')
    CREATE SEQUENCE SEQ_RELATORIO_VIABILIDADE START WITH 1 INCREMENT BY 1;
